### PR TITLE
rtl8723du: fix authentication failures on 5.12+

### LINKED ISSUE #12: Authentication failures on 5.13.0-27-generic
NetworkManager can list the available Wi-Fi networks but it’s impossible to connect to any of them (authentication fails). The issue is due to 9690f34fc2603d04b53432df4e3d6c282f3d1ca6, which introduces a bug, as in the `#else` branch the `rtw_napi_gro_receive(&adapt->napi, pskb)` subroutine is no longer called at all.

I believe the intent was to stop checking for `GRO_DROP`, but the entire call was removed as an accident. A similar issue and fix in another repo:
* https://github.com/aircrack-ng/rtl8812au/issues/855
* https://github.com/aircrack-ng/rtl8812au/pull/857/files

### PR DESCRIPTION
**Pull request by int-index**
closes #12

### CODE REVIEW

**Comment by int-index** [comment]
Probably needs a backport to `v5.13.4`, since that’s the branch that the README.md recommends?

**Comment by lwfinger** [comment]
Thanks.

**Comment by lars75007** [comment]
hello, i have put ubuntu 21.10 on an evolve 3 maestro laptop and used cell-usb-tether to get rtl8723du (downloaded yesterday from git hub) compiled and installed. the laptop now sees the wifi environment, but my wifi password does not get accepted. my password is 10 digit numeric, i don't know if that has anything to do with it - if it's being read as an integer vs string. anyway, i am wondering if this is a known issue, (sounds like this topic - authentication failure) or if i can supply any log excerpts to help the diagnosis. i did look at /var/log/syslog & there are some entries - a block of about 6 warnings, but they are separated from the entries that mention my network name. anyway, pls advise how i can help. i am rusty, but am capable of editing the code & re-making on my machine for testing.
r/lars.

**Comment by lwfinger** [comment]
What encryption method are you trying to use? WEP requires an integer password. If you use WPA, WPA2, or WPA3, then the secret is read as a string; however, I doubt that this driver supports WPA3.

Determine the device name using 'iw dev | grep Interface'. Then use that name in the command
sudo iw dev <Name found above> scan > scan.txt 2>&1

Attach the file scan.txt to this issue.

**Comment by psycocarrot** [comment]
LWFINGER, 

I have recently bought the exact same laptop (Evolve III Maestro) as @lars75007, and am having the same issue where the wifi fails to authenticate properly. I'd like to assist getting the issue resolved. I installed this driver with "make sign-install" and imported the MOK. Everything works properly up until the wifi system attempts to authenticate my PSK.

I have attached the results of the iw dev scan to this comment as "scan.txt". My SSIDs are the ones prefixed with "20723", and they are all WPA2. I am also pasting a snippet of my journalctl output that shows the auth failures, this chunk of text repeats over and over again while attempting to connect to the wifi. Please let me know what other information you need and I'll be happy to get it for you.

Thank you, 
Thomas

[jctl.txt](https://github.com/lwfinger/rtl8723du/files/8190030/jctl.txt)
[scan.txt](https://github.com/lwfinger/rtl8723du/files/8190031/scan.txt)

**Comment by lwfinger** [comment]
There are no indications of the problem in the above attachments.

Does your system have a file /var/log/wpa_supplicant.log? If so, please attach it. In addition, please post the output of the command 'ps ax | grep supp'.

**Comment by lars75007** [comment]
hi, new to this. lwfinger: i got your email and replied to it via email, but i did not enter it in this 'issue'. i am assuming that you got my emails. pls advise if you did not.  in any case, mine seems to work now, but i believe occasionally it is hanging up & i have to cycle wifi-off-on.  just fyi and i know you were talking to thomas, but my system does not have wpp_supplicant.log, and ps yields:  473 ?  Ss  0:03 /sbin/wpa_supplicant -u -s -o /run/wpa_supplicant
let me know if you think it useful to re-post my email texts in this thread.
thanks for your efforts.

**Comment by psycocarrot** [comment]
LWFINGER,

My system didn't have the log by default, but I was able to add the "-f /var/log/wpa_supplicant.log" flag to the systemd servicefile which allowed me to capture some logs, which are attached. I should mention, I have 2x wireless access points in my house, which is probably why there are 2 MAC addresses showing for the "20723" SSID in the log. I have also attached the file "/etc/wpa_supplicant/wpa_supplicant.conf". I also wanted to note that my OS is Fedora 35 with the standard GNOME UI.

The output of "ps ax | grep supp" is as follows:
`   3643 ?        Ss     0:01 /usr/sbin/wpa_supplicant -f /var/log/wpa_supplicant.log -c /etc/wpa_supplicant/wpa_supplicant.conf -u -s
`

Thank you, 
Thomas

[wpa_supplicant.log](https://github.com/lwfinger/rtl8723du/files/8191905/wpa_supplicant.log)
[wpa_supplicant.conf.txt](https://github.com/lwfinger/rtl8723du/files/8191910/wpa_supplicant.conf.txt)

**Pull request merged**
